### PR TITLE
Changed Creative commons to GPL

### PR DESCRIPTION
**Pull request by DeastinY**
And also renamed `LICENSE.txt` to `LICENSE`.
[From the Creative Commons FAQ:](https://creativecommons.org/faq/#Can_I_apply_a_Creative_Commons_license_to_software.3F)
## Can I apply a Creative Commons license to software?

We do not recommend it. Creative Commons licenses should not be used for software. We strongly encourage you to use one of the very good software licenses which are already available. We recommend considering licenses made available by the Free Software Foundation or listed at the Open Source Initiative. Unlike our licenses, which do not make mention of source or object code, these existing licenses were designed specifically for use with software. Furthermore, our licenses are not compatible with the GPL, the most frequently used free software license.

Note that the CC0 Public Domain Dedication is GPL-compatible and acceptable for software. For details, see the relevant CC0 FAQ entry.

### CODE REVIEW

**Review by Fightbackman — APPROVED** [review]
I support. GPL is the better solution

**Comment by thies23** [comment]
We don't own the template and the publisher distributes it under cc license, so we need to stay with this license.

**Comment by DeastinY** [comment]
https://html5up.net/license

> All of the site templates I create for HTML5 UP are licensed under the Creative Commons Attribution 3.0 License, which means you can:
> 
> ```
> Use them for personal stuff
> Use them for commercial stuff
> Change them however you like
> ```
> 
> ... all for free, yo. In exchange, just give HTML5 UP credit for the design and tell your friends about it :)

I'd still suggest using GPL. The author is mentioned on the Github and is linked on the webpage.

**Comment by Fightbackman** [comment]
Would prefer to change to a Software instead of a medialicense if it is possible

Am 9. Oktober 2016 21:09:47 MESZ, schrieb DeastinY notifications@github.com:

> https://html5up.net/license
> 
> > All of the site templates I create for HTML5 UP are licensed under
> > the Creative Commons Attribution 3.0 License, which means you can:
> > 
> > ```
> > Use them for personal stuff
> > Use them for commercial stuff
> > Change them however you like
> > ```
> > 
> > ... all for free, yo. In exchange, just give HTML5 UP credit for the
> > design and tell your friends about it :)
> 
> I'd still suggest using GPL. The author is mentioned on the Github and
> is linked on the webpage.
> 
> ## 
> 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/GOCc3/gocc3-website/pull/15#issuecomment-252505821

## 

Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Pull request merged**
